service: jiphy

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
      Resource:
        Fn::GetAtt:
          - jiphy
          - Arn
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
      Resource:
        Fn::GetAtt:
          - jiphy
          - Arn
  deploymentBucket:
    blockPublicAccess: true

functions:
  jiphy:
    handler: jiphy
    url: true
    environment:
      DYNAMO_TABLE_NAME: ${env:DYNAMO_TABLE_NAME}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

resources:
  Resources:
    jiphy:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMO_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: image_name
            AttributeType: S
        KeySchema:
          - AttributeName: image_name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
