name: build

on:
  push:
    branches:
      - 'main'

env:
  DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go env
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: make build

      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy
        run: cdk deploy
