name: build

on: [push]

env:
  GOOS: linux
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install -g serverless

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.19
    - run: go build

    - run: sls deploy
